[package]
name = "dgcount"
version = "0.1.2"
edition = "2024"
authors = ["Noam Teyssier"]
description = "Dual guide CRISPR counter"
license = "MIT"
repository = "https://github.com/noamteyssier/dgcount"
keywords = ["CRISPR", "dual", "guide", "sgRNA", "counter"]
categories = ["command-line-utilities", "science::bioinformatics"]

[dependencies]
anyhow = "1.0.102"
binseq = "0.9.0"
clap = { version = "4.5.60", features = ["derive"] }
csv = "1.4.0"
num_cpus = "1.17.0"
parking_lot = "0.12.5"
seqhash = "0.1.5"
serde = { version = "1.0.228", features = ["derive"] }
